### ISSUE TITLE
Comma-separated numbers in a string doesn't work

### ISSUE THREAD

**Issue by mikong** [devongovett/coffeepack#6]
Hi,

The following simple case doesn't seem to work:

```
a = '50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75'
b = msgpack.pack(a)
msgpack.unpack(b) # not same as a!
```

**Comment by devongovett** [comment]
Wow, sorry about that.  Should be fixed now.  Was actually a regression in v0.2.0 not caught by the tests so I've included your test as well. :)

**Comment by devongovett** [comment]
Oh and I just released v0.2.2 with the fix.

**Comment by mikong** [comment]
Great! Thanks

**Comment by mikong** [comment]
Hello again! A friend just posted logs to me on how even version 0.2.2 still doesn't work. Are the tests really passing?

**Comment by mikong** [comment]
Nevermind. He only got the updated coffee without the compiled js that's why it wasn't working. Thanks
